theme: jekyll-theme-cayman
title: Mixbus 7 TouchOSC Mk1 Layout
description: It's about a remote control for Harrison's Mixbus version 7.
It lets you set range markers intuitively to mark a loop or a punch area, recording controls include count in and preroll recordings, jog wheel lets you easily relocate song position on the fly, keep track of your recording by managing position markers.
(TODO: Describe all panels)

